services:
    horizon:
      container_name: horizon_1
      build: 
        context: ./.docker
      restart: always
      userns_mode: "keep-id"
      volumes:
        - .:/app/:Z
      ports:
        - 7040:7040
        - 8980:8980